# -*- coding: utf-8 -*-
"""multi Language Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mm7b0blg0MPktcm0tKQO3OYnoGJeL0Gb
"""

from langdetect import detect, DetectorFactory

DetectorFactory.seed = 0

def detect_language(text):
    """
    Detects the language of the input text and returns the ISO code.
    Defaults to 'en' if detection fails.
    """
    if not text or not text.strip():
        return "en"

    try:
        return detect(text)
    except Exception as e:
        print(f"Language detection error: {e}")
        return "en"


sample_text = "調子はどう？"
detected = detect_language(sample_text)
print(f"Detected language for '{sample_text}': {detected}")

M2M_100_LANGUAGES = {
    "Afrikaans": "af", "Amharic": "am", "Arabic": "ar", "Asturian": "ast", "Azerbaijani": "az",
    "Bashkir": "ba", "Belarusian": "be", "Bengali": "bn", "Bhojpuri": "bh", "Bosnian": "bs",
    "Breton": "br", "Bulgarian": "bg", "Burmese": "my", "Catalan": "ca", "Cebuano": "ceb",
    "Chinese": "zh", "Croatian": "hr", "Czech": "cs", "Danish": "da", "Dutch": "nl",
    "English": "en", "Estonian": "et", "Farsi": "fa", "Finnish": "fi", "French": "fr",
    "Fula": "ff", "Galician": "gl", "Ganda": "lg", "Georgian": "ka", "German": "de",
    "Greek": "el", "Gujarati": "gu", "Haitian Creole": "ht", "Hausa": "ha", "Hebrew": "he",
    "Hindi": "hi", "Hungarian": "hu", "Icelandic": "is", "Igbo": "ig", "Indonesian": "id",
    "Irish": "ga", "Italian": "it", "Japanese": "ja", "Javanese": "jv", "Kannada": "kn",
    "Kazakh": "kk", "Khmer": "km", "Korean": "ko", "Kurdish": "ku", "Kyrgyz": "ky",
    "Lao": "lo", "Latvian": "lv", "Lingala": "ln", "Lithuanian": "lt", "Luxembourgish": "lb",
    "Macedonian": "mk", "Malagasy": "mg", "Malay": "ms", "Malayalam": "ml", "Marathi": "mr",
    "Mongolian": "mn", "Mossi": "mos", "Nepali": "ne", "Northern Sotho": "ns", "Norwegian": "no",
    "Occitan": "oc", "Oriya": "or", "Oromo": "om", "Pashto": "ps", "Polish": "pl",
    "Portuguese": "pt", "Punjabi": "pa", "Romanian": "ro", "Russian": "ru", "Sanskrit": "sa",
    "Scottish Gaelic": "gd", "Serbian": "sr", "Sindhi": "sd", "Sinhala": "si", "Slovak": "sk",
    "Slovenian": "sl", "Somali": "so", "Spanish": "es", "Sundanese": "su", "Swahili": "sw",
    "Swedish": "sv", "Tagalog": "tl", "Tamil": "ta", "Tatar": "tt", "Telugu": "te",
    "Thai": "th", "Tibetan": "bo", "Turkish": "tr", "Ukrainian": "uk", "Urdu": "ur",
    "Uzbek": "uz", "Vietnamese": "vi", "Welsh": "cy", "Wolof": "wo", "Xhosa": "xh",
    "Yiddish": "yi", "Yoruba": "yo", "Zulu": "zu"
}


language_names = sorted(list(M2M_100_LANGUAGES.keys()))

print(f"Total languages mapped: {len(M2M_100_LANGUAGES)}")
print("Sample mapping (Name -> Code):")
for name in language_names[:5]:
    print(f" - {name}: {M2M_100_LANGUAGES[name]}")

# Commented out IPython magic to ensure Python compatibility.
# Install necessary libraries for translation model
# %pip install transformers torch

from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer
import torch

# Initialize M2M100 model and tokenizer
model_name = "facebook/m2m100_418M"
tokenizer = M2M100Tokenizer.from_pretrained(model_name)
model = M2M100ForConditionalGeneration.from_pretrained(model_name)

# Check if CUDA is available and move model to GPU if it is
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

def translate_text(text, source_lang_code, target_lang_code):
    """
    Translates text from source_lang_code to target_lang_code using M2M100 model.
    """
    tokenizer.src_lang = source_lang_code
    encoded_text = tokenizer(text, return_tensors="pt").to(device)
    generated_tokens = model.generate(**encoded_text, forced_bos_token_id=tokenizer.get_lang_id(target_lang_code))
    return tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]



# Commented out IPython magic to ensure Python compatibility.
# %pip install gradio

import gradio as gr

def enhanced_translate(text, target_language_name):
    if not text.strip():
        return "", "Please enter text to translate."

    # 1. Detect source language
    src_lang_code = detect_language(text)

    # 2. Get target language code from mapping
    tgt_lang_code = M2M_100_LANGUAGES.get(target_language_name, "en")

    # 3. Perform translation
    translation = translate_text(text, src_lang_code, tgt_lang_code)

    status = f"Detected Source: {src_lang_code.upper()} | Translated to: {target_language_name}"
    return translation, status

# Custom CSS for Professional Dark Mode aesthetic
custom_css = """
body { background-color: #0b0f19 !important; }
.gradio-container { background-color: #0b0f19 !important; color: #e5e7eb !important; }
footer { display: none !important; }
"""

with gr.Blocks() as demo:
    gr.Markdown("# 🌍 Multi-Language Translator")
    gr.Markdown("### IBM Internship Project: AI-Powered Translator with Language Detection")

    with gr.Row():
        with gr.Column(scale=1):
            input_text = gr.Textbox(
                label="Input Text",
                placeholder="Type or paste text here...",
                lines=8
            )
            target_lang = gr.Dropdown(
                choices=language_names,
                value="Hindi",
                label="Target Language"
            )

            with gr.Row():
                clear_btn = gr.Button("Clear", variant="secondary")
                submit_btn = gr.Button("Translate", variant="primary")

        with gr.Column(scale=1):
            output_text = gr.Textbox(label="Translation Result", lines=8, interactive=False)
            status_bar = gr.Label(label="System Status", value="Ready")

    gr.Examples(
        examples=[
            ["Hello, My name is Amit", "Spanish"],
            ["Bonjour, je m'appelle Amit", "English"],
            ["Watashinonamaeha amittodesu?", "German"]
        ],
        inputs=[input_text, target_lang]
    )

    # Define interactions
    submit_btn.click(
        fn=enhanced_translate,
        inputs=[input_text, target_lang],
        outputs=[output_text, status_bar]
    )

    clear_btn.click(
        lambda: [None, "Hindi", None, "Ready"],
        outputs=[input_text, target_lang, output_text, status_bar]
    )

print("Launching enhanced interface...")
demo.launch(share=True)

